const sights_data = [
    // =================================================================
    // TOP 10: DE ICONEN
    // =================================================================
    { id: 101, rank: 1, type: 'sight', tag: 'culture', region: 'bangkok', name: "The Grand Palace", lat: 13.7500, lng: 100.4915, price: "€ 13,50", desc: "Het officiële verblijf van de koningen van Siam." },
    { id: 102, rank: 2, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Arun", lat: 13.7437, lng: 100.4888, price: "€ 5,40", desc: "Tempel van de Dageraad met iconische porseleinen toren." },
    { id: 103, rank: 3, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Pho", lat: 13.7465, lng: 100.4933, price: "€ 8,10", desc: "Huis van de liggende Boeddha en traditionele massage." },
    { id: 104, rank: 4, type: 'sight', tag: 'culture', region: 'bangkok', name: "Chatuchak Weekend Market", lat: 13.7998, lng: 100.5504, price: "Gratis", desc: "Grootste markt ter wereld met 15.000 kraampjes." },
    { id: 105, rank: 5, type: 'sight', tag: 'culture', region: 'bangkok', name: "Ayutthaya Historical Park", lat: 14.3532, lng: 100.5684, price: "€ 1,35", desc: "Ruïnes van de oude hoofdstad, UNESCO werelderfgoed." },
    { id: 106, rank: 6, type: 'sight', tag: 'nature', region: 'south', name: "Khao Sok National Park", lat: 8.9135, lng: 98.5309, price: "€ 8,10", desc: "Oerwoud ouder dan de Amazone met kalksteenmeren." },
    { id: 107, rank: 7, type: 'sight', tag: 'culture', region: 'bangkok', name: "Damnoen Saduak Floating Market", lat: 13.5195, lng: 99.9577, price: "Gratis", desc: "De beroemdste drijvende markt van Thailand." },
    { id: 108, rank: 8, type: 'sight', tag: 'culture', region: 'bangkok', name: "Chinatown (Yaowarat)", lat: 13.7410, lng: 100.5085, price: "Gratis", desc: "Bruisend hart van streetfood en handel." },
    { id: 109, rank: 9, type: 'sight', tag: 'nature', region: 'west', name: "Erawan National Park", lat: 14.3755, lng: 99.1440, price: "€ 8,10", desc: "Sprookjesachtige waterval met zeven niveaus." },
    { id: 110, rank: 10, type: 'sight', tag: 'nature', region: 'south', name: "Railay Beach", lat: 8.0110, lng: 98.8373, price: "Gratis", desc: "Kalksteenkliffen en stranden, alleen per boot bereikbaar." },

    // =================================================================
    // 11-50: DE MUST-SEES
    // =================================================================
    { id: 111, rank: 11, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Doi Suthep", lat: 18.8048, lng: 98.9216, price: "€ 0,80", desc: "Gouden tempel op een bergtop boven Chiang Mai." },
    { id: 112, rank: 12, type: 'sight', tag: 'culture', region: 'north', name: "Wat Rong Khun (Witte Tempel)", lat: 19.8243, lng: 99.7632, price: "€ 2,70", desc: "Moderne kunsttempel, overgang van hel naar hemel." },
    { id: 113, rank: 13, type: 'sight', tag: 'culture', region: 'north', name: "Sukhothai Historical Park", lat: 17.0163, lng: 99.7036, price: "€ 2,70", desc: "De eerste hoofdstad van Siam met elegante Boeddha's." },
    { id: 114, rank: 14, type: 'sight', tag: 'nature', region: 'south', name: "Phang Nga Bay", lat: 8.2855, lng: 98.5093, price: "€ 8,10", desc: "Baai vol iconische kalksteenrotsen die uit zee rijzen." },
    { id: 115, rank: 15, type: 'sight', tag: 'culture', region: 'bangkok', name: "Jim Thompson House", lat: 13.7495, lng: 100.5283, price: "€ 5,40", desc: "Teakhouten huis van de man die Thaise zijde beroemd maakte." },
    { id: 116, rank: 16, type: 'sight', tag: 'nature', region: 'south', name: "Koh Phi Phi (Maya Bay)", lat: 7.6775, lng: 98.7663, price: "€ 10,80", desc: "Beroemdste strand van Thailand, bekend van 'The Beach'." },
    { id: 117, rank: 17, type: 'sight', tag: 'nature', region: 'east', name: "Koh Samet", lat: 12.5683, lng: 101.4526, price: "€ 5,40", desc: "Witte stranden op reisafstand van Bangkok." },
    { id: 118, rank: 18, type: 'sight', tag: 'culture', region: 'east', name: "Sanctuary of Truth", lat: 12.9727, lng: 100.8891, price: "€ 13,50", desc: "Gigantisch houten monument aan zee, volledig handgesneden." },
    { id: 119, rank: 19, type: 'sight', tag: 'culture', region: 'bangkok', name: "Asiatique The Riverfront", lat: 13.7045, lng: 100.5034, price: "Gratis", desc: "Shoppen en dineren aan de rivier in oude pakhuizen." },
    { id: 120, rank: 20, type: 'sight', tag: 'nature', region: 'north', name: "Doi Inthanon", lat: 18.5886, lng: 98.4862, price: "€ 8,10", desc: "Het hoogste punt van Thailand met nevelwouden." },
    { id: 121, rank: 21, type: 'sight', tag: 'culture', region: 'bangkok', name: "Golden Mount (Wat Saket)", lat: 13.7538, lng: 100.5066, price: "€ 2,70", desc: "Tempel op een kunstmatige heuvel met uitzicht over oud Bangkok." },
    { id: 122, rank: 22, type: 'sight', tag: 'culture', region: 'bangkok', name: "MahaNakhon SkyWalk", lat: 13.7224, lng: 100.5283, price: "€ 24,00", desc: "Glazen vloer op 314 meter hoogte boven de stad." },
    { id: 123, rank: 23, type: 'sight', tag: 'nature', region: 'north', name: "Elephant Nature Park", lat: 19.2155, lng: 98.8606, price: "€ 67,50", desc: "Pionier in ethische olifantenopvang in Chiang Mai." },
    { id: 124, rank: 24, type: 'sight', tag: 'culture', region: 'bangkok', name: "Lumpini Park", lat: 13.7314, lng: 100.5414, price: "Gratis", desc: "Het groene hart van de stad, vol met varanen." },
    { id: 125, rank: 25, type: 'sight', tag: 'culture', region: 'west', name: "Dragon Descendants Museum", lat: 14.4776, lng: 100.1106, price: "€ 13,00", desc: "Enorm drakenmuseum over de Chinees-Thaise geschiedenis." },
    { id: 126, rank: 26, type: 'sight', tag: 'culture', region: 'bangkok', name: "Erawan Museum", lat: 13.6286, lng: 100.5890, price: "€ 10,80", desc: "Tempel in een gigantische driehoofdige olifant." },
    { id: 127, rank: 27, type: 'sight', tag: 'nature', region: 'east', name: "Koh Larn", lat: 12.9213, lng: 100.7776, price: "Gratis", desc: "Koraaleiland met helder water voor de kust van Pattaya." },
    { id: 128, rank: 28, type: 'sight', tag: 'nature', region: 'east', name: "Koh Chang", lat: 12.0406, lng: 102.3023, price: "Gratis", desc: "Groot, bergachtig eiland met jungle en stranden." },
    { id: 129, rank: 29, type: 'sight', tag: 'culture', region: 'bangkok', name: "Bangkok Art & Culture Centre", lat: 13.7466, lng: 100.5303, price: "Gratis", desc: "Modern centrum voor hedendaagse kunst en design." },
    { id: 130, rank: 30, type: 'sight', tag: 'culture', region: 'north', name: "Chiang Mai Night Bazaar", lat: 18.7856, lng: 99.0003, price: "Gratis", desc: "Beroemde avondmarkt voor souvenirs en handwerk." },
    { id: 131, rank: 31, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Traimit", lat: 13.7383, lng: 100.5141, price: "€ 1,10", desc: "Huis van de grootste massief gouden Boeddha ter wereld." },
    { id: 132, rank: 32, type: 'sight', tag: 'culture', region: 'bangkok', name: "Talad Noi", lat: 13.7346, lng: 100.5133, price: "Gratis", desc: "Oudste wijk van Bangkok, vol streetart en auto-onderdelen." },
    { id: 133, rank: 33, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra Singh", lat: 18.7886, lng: 98.9818, price: "€ 1,10", desc: "Het mooiste voorbeeld van Lanna-architectuur in Chiang Mai." },
    { id: 134, rank: 34, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chedi Luang", lat: 18.7870, lng: 98.9866, price: "€ 1,10", desc: "Grote ruïne-stoepa in het centrum van Chiang Mai." },
    { id: 135, rank: 35, type: 'sight', tag: 'culture', region: 'north', name: "Baan Dam (Black House)", lat: 19.9922, lng: 99.8605, price: "€ 2,15", desc: "Duister museumcomplex, de tegenhanger van de Witte Tempel." },
    { id: 136, rank: 36, type: 'sight', tag: 'culture', region: 'north', name: "Golden Triangle", lat: 20.3533, lng: 100.0833, price: "Gratis", desc: "Historisch drielandenpunt Thailand, Laos, Myanmar." },
    { id: 137, rank: 37, type: 'sight', tag: 'culture', region: 'north', name: "Wat Rong Suea Ten (Blauwe Tempel)", lat: 19.9233, lng: 99.8419, price: "Gratis", desc: "Opvallende blauwe tempel met indrukwekkend interieur." },
    { id: 138, rank: 38, type: 'sight', tag: 'nature', region: 'north', name: "Pai Canyon", lat: 19.3060, lng: 98.4526, price: "Gratis", desc: "Smalle zandsteenruggen en diepe afgronden bij zonsondergang." },
    { id: 139, rank: 39, type: 'sight', tag: 'culture', region: 'west', name: "Wat Tham Suea (Kanchanaburi)", lat: 13.9535, lng: 99.6053, price: "Gratis", desc: "Enorme Boeddha met uitzicht over de rijstvelden." },
    { id: 140, rank: 40, type: 'sight', tag: 'nature', region: 'west', name: "Sai Yok National Park", lat: 14.4397, lng: 98.8559, price: "€ 8,10", desc: "Watervallen die direct in de rivier de Kwai stromen." },
    { id: 141, rank: 41, type: 'sight', tag: 'culture', region: 'bangkok', name: "Maeklong Railway Market", lat: 13.4075, lng: 99.9987, price: "Gratis", desc: "De markt waar de trein dwars doorheen rijdt." },
    { id: 142, rank: 42, type: 'sight', tag: 'culture', region: 'bangkok', name: "Bang Pa-In Palace", lat: 14.2323, lng: 100.5796, price: "€ 2,70", desc: "Zomerpaleis van de koningen met diverse architectuurstijlen." },
    { id: 143, rank: 43, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chaloem Phra Kiat", lat: 18.7413, lng: 99.5436, price: "€ 5,40", desc: "Zwevende pagodes op messcherpe kalksteenpieken." },
    { id: 144, rank: 44, type: 'sight', tag: 'nature', region: 'south', name: "James Bond Island", lat: 8.2750, lng: 98.5000, price: "€ 8,10", desc: "De beroemde rots uit 'The Man with the Golden Gun'." },
    { id: 145, rank: 45, type: 'sight', tag: 'nature', region: 'north', name: "Mae Hong Son Loop", lat: 19.3020, lng: 97.9654, price: "Gratis", desc: "Beroemde motorroute met 1864 bochten door de bergen." },
    { id: 146, rank: 46, type: 'sight', tag: 'culture', region: 'bangkok', name: "Victory Monument", lat: 13.7649, lng: 100.5383, price: "Gratis", desc: "Militair monument en knooppunt van lokaal leven." },
    { id: 147, rank: 47, type: 'sight', tag: 'culture', region: 'south', name: "Big Buddha Phuket", lat: 7.8276, lng: 98.3126, price: "Gratis", desc: "Enorm wit marmeren beeld op een heuveltop." },
    { id: 148, rank: 48, type: 'sight', tag: 'nature', region: 'east', name: "Nong Nooch Tropical Garden", lat: 12.7663, lng: 100.9335, price: "€ 13,50", desc: "Prachtig aangelegde botanische tuinen in Pattaya." },
    { id: 149, rank: 49, type: 'sight', tag: 'culture', region: 'west', name: "Mallika City", lat: 14.0436, lng: 99.2938, price: "€ 6,75", desc: "Levend museum dat het leven in 1905 nabootst." },
    { id: 150, rank: 50, type: 'sight', tag: 'culture', region: 'bangkok', name: "Museum of Contemporary Art (MOCA)", lat: 13.8523, lng: 100.5627, price: "€ 6,75", desc: "Indrukwekkende collectie moderne Thaise kunst." },

    // =================================================================
    // 51-100: REGIONALE PARELS & CULTUUR
    // =================================================================
    { id: 151, rank: 51, type: 'sight', tag: 'culture', region: 'east', name: "Phanom Rung Historical Park", lat: 14.5323, lng: 102.9426, price: "€ 2,70", desc: "Khmer-tempel op de rand van een uitgedoofde vulkaan." },
    { id: 152, rank: 52, type: 'sight', tag: 'culture', region: 'east', name: "Phimai Historical Park", lat: 15.2203, lng: 102.4939, price: "€ 2,70", desc: "De grootste Khmer-tempel in Thailand." },
    { id: 153, rank: 53, type: 'sight', tag: 'nature', region: 'east', name: "Sam Pan Bok", lat: 15.8033, lng: 105.3855, price: "Gratis", desc: "De 'Grand Canyon' van Thailand in de Mekong-rivier." },
    { id: 154, rank: 54, type: 'sight', tag: 'nature', region: 'east', name: "Red Lotus Lake", lat: 17.2210, lng: 103.0381, price: "€ 10,00", desc: "Meer dat verandert in een roze bloemenzee (dec-feb)." },
    { id: 155, rank: 55, type: 'sight', tag: 'culture', region: 'east', name: "Wat Phu Tok", lat: 18.1319, lng: 103.8827, price: "Gratis", desc: "Tempel met houten loopbruggen rondom een eenzame rots." },
    { id: 156, rank: 56, type: 'sight', tag: 'culture', region: 'east', name: "Sala Keoku", lat: 17.8864, lng: 102.7786, price: "€ 1,10", desc: "Beeldentuin met bizarre, enorme cementen beelden." },
    { id: 157, rank: 57, type: 'sight', tag: 'culture', region: 'east', name: "Prasat Muang Tam", lat: 14.4983, lng: 102.9819, price: "€ 2,70", desc: "Khmer tempel bekend om zijn vijvers en Naga's." },
    { id: 158, rank: 58, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Lampang Luang", lat: 18.2173, lng: 99.3900, price: "Gratis", desc: "Een van de best bewaarde houten Lanna-tempels." },
    { id: 159, rank: 59, type: 'sight', tag: 'culture', region: 'north', name: "Wat Sri Chum (Sukhothai)", lat: 17.0271, lng: 99.6936, price: "€ 2,70", desc: "Enorme zittende Boeddha in een krappe stenen omhulling." },
    { id: 160, rank: 60, type: 'sight', tag: 'culture', region: 'bangkok', name: "Phra Sumen Fort", lat: 13.7635, lng: 100.4952, price: "Gratis", desc: "Wit fort aan de rivier in een rustig park." },
    { id: 161, rank: 61, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Benchamabophit", lat: 13.7666, lng: 100.5141, price: "€ 1,35", desc: "De Marmeren Tempel, een mix van Thais en Europees design." },
    { id: 162, rank: 62, type: 'sight', tag: 'culture', region: 'bangkok', name: "Snake Farm (Queen Saovabha)", lat: 13.7324, lng: 100.5317, price: "€ 5,40", desc: "Educatief instituut over slangen en tegengif." },
    { id: 163, rank: 63, type: 'sight', tag: 'nature', region: 'east', name: "Khao Yai National Park", lat: 14.4390, lng: 101.3725, price: "€ 10,80", desc: "Oudste nationale park, kans op wilde olifanten en gibbons." },
    { id: 164, rank: 64, type: 'sight', tag: 'culture', region: 'bangkok', name: "Museum of Siam", lat: 13.7441, lng: 100.4941, price: "€ 5,40", desc: "Interactief museum over de Thaise identiteit." },
    { id: 165, rank: 65, type: 'sight', tag: 'culture', region: 'west', name: "Wat Tham Suea (Tiger Cave Kanchanaburi)", lat: 13.9537, lng: 99.6053, price: "Gratis", desc: "Grote Boeddha en uitzicht over de rijstvelden." },
    { id: 166, rank: 66, type: 'sight', tag: 'culture', region: 'west', name: "Giant Rain Tree", lat: 13.9553, lng: 99.5273, price: "Gratis", desc: "Gigantische regenboom van meer dan 100 jaar oud." },
    { id: 167, rank: 67, type: 'sight', tag: 'culture', region: 'west', name: "Malika R.E. 124", lat: 14.0436, lng: 99.2938, price: "€ 6,75", desc: "Retrodorp waar je betaalt met oud geld en klederdracht draagt." },
    { id: 168, rank: 68, type: 'sight', tag: 'culture', region: 'west', name: "Death Railway Museum", lat: 14.0326, lng: 99.5250, price: "€ 4,00", desc: "Informatief museum over de geschiedenis van de spoorlijn." },
    { id: 169, rank: 69, type: 'sight', tag: 'culture', region: 'west', name: "Phra Pathom Chedi", lat: 13.8197, lng: 100.0601, price: "€ 1,60", desc: "De hoogste stoepa ter wereld in Nakhon Pathom." },
    { id: 170, rank: 70, type: 'sight', tag: 'culture', region: 'west', name: "Wat Samphran (Dragon Temple)", lat: 13.7347, lng: 100.2155, price: "Donatie", desc: "Roze toren met een gigantische draak eromheen gewikkeld." },
    { id: 171, rank: 71, type: 'sight', tag: 'culture', region: 'west', name: "Prasat Muang Singh", lat: 14.0396, lng: 99.2435, price: "€ 2,70", desc: "Khmer-ruïnes in het uiterste westen." },
    { id: 172, rank: 72, type: 'sight', tag: 'culture', region: 'west', name: "Bridge Over the River Kwai", lat: 14.0410, lng: 99.5042, price: "Gratis", desc: "De beruchte brug uit de Tweede Wereldoorlog." },
    { id: 173, rank: 73, type: 'sight', tag: 'culture', region: 'west', name: "Hellfire Pass", lat: 14.3528, lng: 98.9536, price: "Gratis", desc: "Wandelroute door de uitgehakte rotskloof van de spoorlijn." },
    { id: 174, rank: 74, type: 'sight', tag: 'nature', region: 'west', name: "Mon Bridge (Sangkhlaburi)", lat: 15.1436, lng: 98.4503, price: "Gratis", desc: "Langste houten brug van Thailand, verbindt culturen." },
    { id: 175, rank: 75, type: 'sight', tag: 'nature', region: 'west', name: "Pom Pee Viewpoint", lat: 14.8878, lng: 98.5772, price: "€ 8,10", desc: "Prachtig uitzichtpunt over het stuwmeer in Khao Laem NP." },
    { id: 176, rank: 76, type: 'sight', tag: 'nature', region: 'south', name: "Cheow Lan Lake", lat: 8.9767, lng: 98.8203, price: "€ 8,10", desc: "Het hart van Khao Sok, varen tussen kalksteenrotsen." },
    { id: 177, rank: 77, type: 'sight', tag: 'culture', region: 'south', name: "Wat Phra Mahathat", lat: 8.4103, lng: 99.9659, price: "Gratis", desc: "Belangrijkste tempel van Zuid-Thailand in Nakhon Si Thammarat." },
    { id: 178, rank: 78, type: 'sight', tag: 'nature', region: 'south', name: "Kiriwong Village", lat: 8.4419, lng: 99.7633, price: "Gratis", desc: "Dorp met de schoonste lucht van Thailand." },
    { id: 179, rank: 79, type: 'sight', tag: 'nature', region: 'south', name: "Thale Noi Waterfowl Park", lat: 7.7836, lng: 100.1264, price: "Gratis", desc: "Moerasgebied vol lotusbloemen en watervogels." },
    { id: 180, rank: 80, type: 'sight', tag: 'culture', region: 'south', name: "Songkhla Old Town", lat: 7.1936, lng: 100.5925, price: "Gratis", desc: "Historische wijk met Chinees-Europese architectuur." },
    { id: 181, rank: 81, type: 'sight', tag: 'nature', region: 'south', name: "Phi Phi Islands (Maya Bay)", lat: 7.6775, lng: 98.7663, price: "€ 10,80", desc: "Wereldberoemde baai, nu ecologisch herstellende." },
    { id: 182, rank: 82, type: 'sight', tag: 'nature', region: 'south', name: "Pileh Lagoon", lat: 7.6833, lng: 98.7667, price: "Gratis", desc: "Smaragdgroene lagune omringd door hoge kliffen." },
    { id: 183, rank: 83, type: 'sight', tag: 'nature', region: 'south', name: "Samet Nangshe Viewpoint", lat: 8.2406, lng: 98.4485, price: "€ 0,80", desc: "Het ultieme uitzicht over de baai van Phang Nga." },
    { id: 184, rank: 84, type: 'sight', tag: 'nature', region: 'south', name: "Koh Panyee", lat: 8.3364, lng: 98.5025, price: "Gratis", desc: "Drijvend moslimdorp op palen in Phang Nga Bay." },
    { id: 185, rank: 85, type: 'sight', tag: 'nature', region: 'south', name: "Similan Islands", lat: 8.6536, lng: 97.6433, price: "€ 13,50", desc: "Wereldklasse duik- en snorkelplek (gesloten mei-okt)." },
    { id: 186, rank: 86, type: 'sight', tag: 'nature', region: 'south', name: "Surin Islands", lat: 9.4167, lng: 97.8667, price: "€ 13,50", desc: "Ongerepte eilanden, thuisbasis van de Moken zee-zigeuners." },
    { id: 187, rank: 87, type: 'sight', tag: 'nature', region: 'south', name: "Koh Lipe", lat: 6.4884, lng: 99.3039, price: "€ 5,40", desc: "De 'Malediven van Thailand' met turquoise water." },
    { id: 188, rank: 88, type: 'sight', tag: 'nature', region: 'south', name: "Koh Tao", lat: 10.0956, lng: 99.8404, price: "Gratis", desc: "Het eiland om te leren duiken." },
    { id: 189, rank: 89, type: 'sight', tag: 'nature', region: 'south', name: "Ang Thong National Marine Park", lat: 9.6150, lng: 99.6766, price: "€ 8,10", desc: "Archipel van 42 eilanden, bekend van 'The Beach'." },
    { id: 190, rank: 90, type: 'sight', tag: 'nature', region: 'south', name: "Koh Nang Yuan", lat: 10.1167, lng: 99.8167, price: "€ 6,75", desc: "Drie eilandjes verbonden door een zandstrook." },
    { id: 191, rank: 91, type: 'sight', tag: 'nature', region: 'south', name: "Emerald Pool (Krabi)", lat: 7.9232, lng: 99.2603, price: "€ 5,40", desc: "Natuurlijk kristalhelder zwembad in het bos." },
    { id: 192, rank: 92, type: 'sight', tag: 'nature', region: 'south', name: "Hot Springs Waterfall (Krabi)", lat: 7.9317, lng: 99.2081, price: "€ 5,40", desc: "Natuurlijke warme baden in de rotsen." },
    { id: 193, rank: 93, type: 'sight', tag: 'culture', region: 'south', name: "Wat Chalong", lat: 7.8465, lng: 98.3372, price: "Gratis", desc: "De grootste en belangrijkste tempel van Phuket." },
    { id: 194, rank: 94, type: 'sight', tag: 'nature', region: 'south', name: "Aiyerweng Skywalk", lat: 5.9757, lng: 101.1825, price: "€ 5,40", desc: "Glazen platform met uitzicht over de 'Zee van Mist' in Betong." },
    { id: 195, rank: 95, type: 'sight', tag: 'culture', region: 'south', name: "Phuket Old Town", lat: 7.8858, lng: 98.3907, price: "Gratis", desc: "Kleurrijke Sino-Portugese architectuur." },
    { id: 196, rank: 96, type: 'sight', tag: 'culture', region: 'south', name: "Big Buddha Samui", lat: 9.5707, lng: 100.0604, price: "Gratis", desc: "Gouden Boeddha op een eilandje voor de kust." },
    { id: 197, rank: 97, type: 'sight', tag: 'nature', region: 'south', name: "Hin Ta & Hin Yai", lat: 9.4523, lng: 100.0396, price: "Gratis", desc: "Beroemde rotsformaties op Koh Samui." },
    { id: 198, rank: 98, type: 'sight', tag: 'nature', region: 'east', name: "Koh Mak", lat: 11.8167, lng: 102.4833, price: "Gratis", desc: "Rustig eiland, perfect om te fietsen en relaxen." },
    { id: 199, rank: 99, type: 'sight', tag: 'culture', region: 'bangkok', name: "Bangkok National Museum", lat: 13.7573, lng: 100.4922, price: "€ 5,40", desc: "Grootste collectie Thaise kunst en artefacten." },
    { id: 200, rank: 100, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Hariphunchai", lat: 18.5772, lng: 99.0083, price: "€ 0,55", desc: "Belangrijke tempel in Lamphun met een gouden stoepa." },

    // =================================================================
    // 101-150: VERBORGEN PARELS & CULTUUR
    // =================================================================
    { id: 801, rank: 101, type: 'sight', tag: 'culture', region: 'north', name: "Baan Jang Nak", lat: 18.7364, lng: 99.0350, price: "Gratis", desc: "Museum van olifantenhoutsnijwerk." },
    { id: 802, rank: 102, type: 'sight', tag: 'nature', region: 'east', name: "Koh Kood", lat: 11.6667, lng: 102.5667, price: "Gratis", desc: "Ongerept eiland met kristalhelder water." },
    { id: 803, rank: 103, type: 'sight', tag: 'culture', region: 'north', name: "Wat Umong", lat: 18.7834, lng: 98.9517, price: "Gratis", desc: "Bostempel met tunnels en een vredige sfeer." },
    { id: 804, rank: 104, type: 'sight', tag: 'culture', region: 'bangkok', name: "Princess Mother Memorial Park", lat: 13.7363, lng: 100.4994, price: "Gratis", desc: "Prachtig park en museum ter ere van de prinses-moeder." },
    { id: 805, rank: 105, type: 'sight', tag: 'culture', region: 'bangkok', name: "M.R. Kukrit's House", lat: 13.7199, lng: 100.5307, price: "€ 1,35", desc: "Erfgoedhuis van een voormalige premier." },
    { id: 806, rank: 106, type: 'sight', tag: 'culture', region: 'bangkok', name: "Suan Pakkad Palace", lat: 13.7573, lng: 100.5367, price: "€ 2,70", desc: "Museumcomplex in traditionele huizen." },
    { id: 807, rank: 107, type: 'sight', tag: 'culture', region: 'east', name: "Sanctuary of Truth", lat: 12.9727, lng: 100.8891, price: "€ 13,50", desc: "Gigantisch houten monument aan zee, volledig handgesneden." },
    { id: 808, rank: 108, type: 'sight', tag: 'nature', region: 'east', name: "Mini Siam", lat: 12.9547, lng: 100.9090, price: "€ 8,10", desc: "Miniatuurpark met beroemde gebouwen." },
    { id: 809, rank: 109, type: 'sight', tag: 'nature', region: 'east', name: "Silverlake Vineyard", lat: 12.7634, lng: 100.9634, price: "Gratis", desc: "Wijngaard met Italiaanse architectuur nabij Pattaya." },
    { id: 810, rank: 110, type: 'sight', tag: 'culture', region: 'east', name: "Buddha Mountain (Khao Chi Chan)", lat: 12.7656, lng: 100.9560, price: "Gratis", desc: "Gouden Boeddha-afbeelding gelaserd in een bergwand." },
    { id: 811, rank: 111, type: 'sight', tag: 'nature', region: 'east', name: "Art in Paradise Pattaya", lat: 12.9479, lng: 100.8893, price: "€ 10,80", desc: "Interactief 3D-kunstmuseum." },
    { id: 812, rank: 112, type: 'sight', tag: 'nature', region: 'east', name: "Ramayana Water Park", lat: 12.7513, lng: 100.9620, price: "€ 32,00", desc: "Grootste waterpark van Thailand." },
    { id: 813, rank: 113, type: 'sight', tag: 'culture', region: 'east', name: "Viharn Sien", lat: 12.7844, lng: 100.9550, price: "€ 1,35", desc: "Chinees tempelmuseum met terracotta strijders." },
    { id: 814, rank: 114, type: 'sight', tag: 'nature', region: 'east', name: "Koh Samet", lat: 12.5683, lng: 101.4526, price: "€ 5,40", desc: "Populair eiland voor een weekend weg vanuit Bangkok." },
    { id: 815, rank: 115, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Doi Kong Mu", lat: 19.3003, lng: 97.9606, price: "Gratis", desc: "Tempel met Shan-invloeden en uitzicht over Mae Hong Son." },
    { id: 816, rank: 116, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chong Kham", lat: 19.2972, lng: 97.9614, price: "Gratis", desc: "Tempel aan het meer in Mae Hong Son." },
    { id: 817, rank: 117, type: 'sight', tag: 'nature', region: 'north', name: "Thung Bua Tong", lat: 18.8922, lng: 98.1333, price: "Gratis", desc: "Velden vol wilde zonnebloemen (november)." },
    { id: 818, rank: 118, type: 'sight', tag: 'culture', region: 'north', name: "Ban Rak Thai", lat: 19.5856, lng: 97.9431, price: "Gratis", desc: "Chinees dorp aan een meer met theeplantages." },
    { id: 819, rank: 119, type: 'sight', tag: 'nature', region: 'north', name: "Pang Ung", lat: 19.4994, lng: 97.9103, price: "Gratis", desc: "Het 'Zwitserland van Thailand', meer met dennenbossen." },
    { id: 820, rank: 120, type: 'sight', tag: 'culture', region: 'north', name: "Doi Tung Royal Villa", lat: 20.2878, lng: 99.8117, price: "€ 2,50", desc: "Koninklijke villa met prachtige tuinen." },
    { id: 821, rank: 121, type: 'sight', tag: 'culture', region: 'north', name: "Hall of Opium", lat: 20.3639, lng: 100.0733, price: "€ 5,40", desc: "Interactief museum over de opiumhandel in de Gouden Driehoek." },
    { id: 822, rank: 122, type: 'sight', tag: 'nature', region: 'north', name: "Phu Chi Fa", lat: 19.8500, lng: 100.4460, price: "Gratis", desc: "Klif met uitzicht op Laos en de zee van mist." },
    { id: 823, rank: 123, type: 'sight', tag: 'nature', region: 'north', name: "Elephant Nature Park", lat: 19.2155, lng: 98.8606, price: "€ 67,50", desc: "Pionier in ethische olifantenopvang." },
    { id: 824, rank: 124, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Pha Sorn Kaew", lat: 16.7900, lng: 101.0378, price: "Gratis", desc: "Kleurrijke mozaïektempel in de bergen van Phetchabun." },
    { id: 825, rank: 125, type: 'sight', tag: 'nature', region: 'north', name: "Phu Tub Berk", lat: 16.9022, lng: 101.1061, price: "Gratis", desc: "Hoogste punt van Phetchabun, bekend om koolvelden en mist." },
    { id: 826, rank: 126, type: 'sight', tag: 'culture', region: 'north', name: "Baan Pa Bong Piang", lat: 18.5283, lng: 98.4239, price: "Gratis", desc: "De mooiste rijstterrassen van Thailand." },
    { id: 827, rank: 127, type: 'sight', tag: 'nature', region: 'north', name: "Ob Luang National Park", lat: 18.2239, lng: 98.4800, price: "€ 2,70", desc: "Kloof met een rivier en prehistorische vondsten." },
    { id: 828, rank: 128, type: 'sight', tag: 'nature', region: 'east', name: "Koh Chang", lat: 12.0406, lng: 102.3023, price: "Gratis", desc: "Groot eiland met jungle en stranden." },
    { id: 829, rank: 129, type: 'sight', tag: 'nature', region: 'east', name: "Koh Mak", lat: 11.8167, lng: 102.4833, price: "Gratis", desc: "Rustig en plat eiland, ideaal om te fietsen." },
    { id: 830, rank: 130, type: 'sight', tag: 'nature', region: 'east', name: "Namtok Phlio National Park", lat: 12.5256, lng: 102.1797, price: "€ 5,40", desc: "Waterval vol met vissen waar je mee kunt zwemmen." },
    { id: 831, rank: 131, type: 'sight', tag: 'culture', region: 'east', name: "Cathedral of the Immaculate Conception", lat: 12.5103, lng: 102.1156, price: "Gratis", desc: "Grootste katholieke kerk van Thailand in Chanthaburi." },
    { id: 832, rank: 132, type: 'sight', tag: 'culture', region: 'east', name: "Chanthaburi Old Town", lat: 12.6114, lng: 102.1136, price: "Gratis", desc: "Historische wijk aan de rivier met diverse invloeden." },
    { id: 833, rank: 133, type: 'sight', tag: 'nature', region: 'east', name: "Kung Krabaen Bay", lat: 12.5714, lng: 101.8975, price: "Gratis", desc: "Koninklijk project voor mangrovebehoud." },
    { id: 834, rank: 134, type: 'sight', tag: 'nature', region: 'east', name: "Pink Stone Courtyard", lat: 12.5539, lng: 102.0622, price: "€ 5,40", desc: "Natuurgebied met unieke roze stenen aan de kust." },
    { id: 835, rank: 135, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phumin", lat: 18.7744, lng: 100.7717, price: "Gratis", desc: "Tempel in Nan beroemd om de 'Fluisterende Man' muurschildering." },
    { id: 836, rank: 136, type: 'sight', tag: 'nature', region: 'north', name: "Doi Samer Dao", lat: 18.3697, lng: 100.4939, price: "€ 2,70", desc: "Bergtop in Nan, perfect voor sterrenkijken." },
    { id: 837, rank: 137, type: 'sight', tag: 'culture', region: 'north', name: "Nan National Museum", lat: 18.7761, lng: 100.7719, price: "€ 2,70", desc: "Museum in een voormalig paleis met de Zwarte Olifantentand." },
    { id: 838, rank: 138, type: 'sight', tag: 'nature', region: 'north', name: "Phu Langka Forest Park", lat: 19.3667, lng: 100.5000, price: "Gratis", desc: "De 'Magic Mountain' van Phayao met uitzicht op kalksteenrotsen." },
    { id: 839, rank: 139, type: 'sight', tag: 'culture', region: 'north', name: "Wat Analayo Thipphayaram", lat: 19.1281, lng: 99.8731, price: "Gratis", desc: "Tempelcomplex op een heuvel met uitzicht over het meer van Phayao." },
    { id: 840, rank: 140, type: 'sight', tag: 'nature', region: 'north', name: "Kwan Phayao", lat: 19.1639, lng: 99.8978, price: "Gratis", desc: "Groot zoetwatermeer, populair voor zonsondergang." },
    { id: 841, rank: 141, type: 'sight', tag: 'culture', region: 'north', name: "Wat Si Khom Kham", lat: 19.1722, lng: 99.8967, price: "Gratis", desc: "Huis van de grootste Boeddha in Lanna-stijl." },
    { id: 842, rank: 142, type: 'sight', tag: 'culture', region: 'north', name: "Lampang Elephant Conservation Center", lat: 18.3589, lng: 99.2550, price: "€ 6,00", desc: "Staatsziekenhuis voor olifanten." },
    { id: 843, rank: 143, type: 'sight', tag: 'culture', region: 'north', name: "Dhanabadee Ceramic Museum", lat: 18.2831, lng: 99.4975, price: "€ 2,70", desc: "Museum over de beroemde 'kippenkommen' van Lampang." },
    { id: 844, rank: 144, type: 'sight', tag: 'culture', region: 'north', name: "Kad Kong Ta",