const sights_data = [
    // TOP 10 ICONEN
    { rank: 1, type: 'sight', tag: 'culture', region: 'bangkok', name: "The Grand Palace", lat: 13.7500, lng: 100.4915, price_thb: 500, desc: "Het officiële verblijf van de koningen van Siam en de Smaragdgroene Boeddha." },
    { rank: 2, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Arun", lat: 13.7437, lng: 100.4888, price_thb: 200, desc: "Tempel van de Dageraad, iconisch om zijn centrale toren met porselein." },
    { rank: 3, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Pho", lat: 13.7465, lng: 100.4933, price_thb: 300, desc: "Huis van de 46 meter lange liggende Boeddha en massageschool." },
    { rank: 4, type: 'sight', tag: 'culture', region: 'bangkok', name: "Chatuchak Weekend Market", lat: 13.7998, lng: 100.5504, price_thb: 0, desc: "Grootste markt ter wereld met meer dan 15.000 kraampjes." },
    { rank: 5, type: 'sight', tag: 'culture', region: 'bangkok', name: "Ayutthaya Historical Park", lat: 14.3532, lng: 100.5684, price_thb: 50, desc: "Ruïnes van de oude hoofdstad, UNESCO werelderfgoed." },
    { rank: 6, type: 'sight', tag: 'nature', region: 'south', name: "Khao Sok National Park", lat: 8.9135, lng: 98.5309, price_thb: 300, desc: "Oerwoud ouder dan de Amazone met spectaculaire kalksteenmeren." },
    { rank: 7, type: 'sight', tag: 'culture', region: 'bangkok', name: "Damnoen Saduak Market", lat: 13.5195, lng: 99.9577, price_thb: 0, desc: "De beroemdste en meest fotogenieke drijvende markt van Thailand." },
    { rank: 8, type: 'sight', tag: 'culture', region: 'bangkok', name: "Chinatown (Yaowarat)", lat: 13.7410, lng: 100.5085, price_thb: 0, desc: "Het grootste en levendigste Chinatown ter wereld, neon en streetfood." },
    { rank: 9, type: 'sight', tag: 'nature', region: 'west', name: "Erawan National Park", lat: 14.3755, lng: 99.1440, price_thb: 300, desc: "Sprookjesachtige waterval met zeven niveaus in het oerwoud." },
    { rank: 10, type: 'sight', tag: 'nature', region: 'south', name: "Railay Beach", lat: 8.0110, lng: 98.8373, price_thb: 0, desc: "Kalksteenkliffen en stranden, alleen per boot bereikbaar." },

    // NOORD & CULTUUR
    { rank: 11, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Doi Suthep", lat: 18.8048, lng: 98.9216, price_thb: 30, desc: "Gouden tempel op een bergtop met uitzicht over heel Chiang Mai." },
    { rank: 12, type: 'sight', tag: 'culture', region: 'north', name: "Wat Rong Khun (Witte Tempel)", lat: 19.8243, lng: 99.7632, price_thb: 100, desc: "Een tempel als modern kunstwerk, symboliseert de overgang van hel naar hemel." },
    { rank: 13, type: 'sight', tag: 'culture', region: 'north', name: "Sukhothai Historical Park", lat: 17.0163, lng: 99.7036, price_thb: 100, desc: "De eerste hoofdstad van Siam met elegante Boeddha's en lotusvijvers." },
    { rank: 14, type: 'sight', tag: 'nature', region: 'south', name: "Phang Nga Bay", lat: 8.2855, lng: 98.5093, price_thb: 300, desc: "Baai vol iconische kalksteenrotsen die loodrecht uit zee rijzen." },
    { rank: 15, type: 'sight', tag: 'culture', region: 'bangkok', name: "Jim Thompson House", lat: 13.7495, lng: 100.5283, price_thb: 200, desc: "Traditioneel teakhouten huis van de man die Thaise zijde beroemd maakte." },
    { rank: 16, type: 'sight', tag: 'nature', region: 'south', name: "Koh Phi Phi (Maya Bay)", lat: 7.6775, lng: 98.7663, price_thb: 400, desc: "Beroemdste strand van Thailand, bekend van de film 'The Beach'." },
    { rank: 17, type: 'sight', tag: 'nature', region: 'east', name: "Koh Samet", lat: 12.5683, lng: 101.4526, price_thb: 200, desc: "Witte stranden op reisafstand van Bangkok, populair in het weekend." },
    { rank: 18, type: 'sight', tag: 'culture', region: 'east', name: "Sanctuary of Truth", lat: 12.9727, lng: 100.8891, price_thb: 500, desc: "Gigantisch houten monument aan zee, volledig handgesneden zonder spijkers." },
    { rank: 19, type: 'sight', tag: 'culture', region: 'bangkok', name: "Asiatique The Riverfront", lat: 13.7045, lng: 100.5034, price_thb: 0, desc: "Shoppen, dineren en entertainment aan de rivier in oude pakhuizen." },
    { rank: 20, type: 'sight', tag: 'nature', region: 'north', name: "Doi Inthanon", lat: 18.5886, lng: 98.4862, price_thb: 300, desc: "Het hoogste punt van Thailand met nevelwouden en koninklijke pagodes." },
    
    // MIDDEN & WEST
    { rank: 21, type: 'sight', tag: 'culture', region: 'bangkok', name: "Golden Mount (Wat Saket)", lat: 13.7538, lng: 100.5066, price_thb: 100, desc: "Tempel op een kunstmatige heuvel met 360-graden uitzicht over oud Bangkok." },
    { rank: 22, type: 'sight', tag: 'culture', region: 'bangkok', name: "MahaNakhon SkyWalk", lat: 13.7224, lng: 100.5283, price_thb: 880, desc: "Glazen vloer op 314 meter hoogte boven de stad." },
    { rank: 23, type: 'sight', tag: 'nature', region: 'north', name: "Elephant Nature Park", lat: 19.2155, lng: 98.8606, price_thb: 2500, desc: "Wereldberoemde pionier in ethische olifantenopvang in Chiang Mai." },
    { rank: 24, type: 'sight', tag: 'culture', region: 'bangkok', name: "Lumpini Park", lat: 13.7314, lng: 100.5414, price_thb: 0, desc: "Het groene hart van de stad, vol met vrij rondlopende varanen." },
    { rank: 25, type: 'sight', tag: 'culture', region: 'west', name: "Dragon Descendants Museum", lat: 14.4776, lng: 100.1106, price_thb: 490, desc: "Enorm museum in de vorm van een draak over de Chinees-Thaise geschiedenis." },
    { rank: 26, type: 'sight', tag: 'culture', region: 'bangkok', name: "Erawan Museum", lat: 13.6286, lng: 100.5890, price_thb: 400, desc: "Tempel in een gigantische driehoofdige olifant van koper." },
    { rank: 27, type: 'sight', tag: 'nature', region: 'east', name: "Koh Larn", lat: 12.9213, lng: 100.7776, price_thb: 0, desc: "Koraaleiland met helder water, direct voor de kust van Pattaya." },
    { rank: 28, type: 'sight', tag: 'nature', region: 'east', name: "Koh Chang", lat: 12.0406, lng: 102.3023, price_thb: 200, desc: "Groot, bergachtig eiland met dichte jungle en rustige stranden." },
    { rank: 29, type: 'sight', tag: 'culture', region: 'bangkok', name: "Bangkok Art & Culture Centre", lat: 13.7466, lng: 100.5303, price_thb: 0, desc: "Modern centrum voor hedendaagse kunst, design en cultuur." },
    { rank: 30, type: 'sight', tag: 'culture', region: 'north', name: "Chiang Mai Night Bazaar", lat: 18.7856, lng: 99.0003, price_thb: 0, desc: "Beroemde avondmarkt voor souvenirs, kleding en handwerk." },
    
    // DE VERBORGEN PARELS
    { rank: 31, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Traimit", lat: 13.7383, lng: 100.5141, price_thb: 40, desc: "Huis van de grootste massief gouden Boeddha (5,5 ton) ter wereld." },
    { rank: 32, type: 'sight', tag: 'culture', region: 'bangkok', name: "Talad Noi", lat: 13.7346, lng: 100.5133, price_thb: 0, desc: "Oudste wijk van Bangkok, vol streetart, auto-onderdelen en cafés." },
    { rank: 33, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra Singh", lat: 18.7886, lng: 98.9818, price_thb: 40, desc: "Het mooiste voorbeeld van klassieke Lanna-architectuur in Chiang Mai." },
    { rank: 34, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chedi Luang", lat: 18.7870, lng: 98.9866, price_thb: 40, desc: "Grote ruïne-stoepa in het centrum van Chiang Mai." },
    { rank: 35, type: 'sight', tag: 'culture', region: 'north', name: "Baan Dam (Black House)", lat: 19.9922, lng: 99.8605, price_thb: 80, desc: "Duister en artistiek museumcomplex, de tegenhanger van de Witte Tempel." },
    { rank: 36, type: 'sight', tag: 'culture', region: 'north', name: "Golden Triangle", lat: 20.3533, lng: 100.0833, price_thb: 0, desc: "Het historische drielandenpunt tussen Thailand, Laos en Myanmar." },
    { rank: 37, type: 'sight', tag: 'culture', region: 'north', name: "Wat Rong Suea Ten (Blauwe Tempel)", lat: 19.9233, lng: 99.8419, price_thb: 0, desc: "Opvallende blauwe tempel met een indrukwekkend, kleurrijk interieur." },
    { rank: 38, type: 'sight', tag: 'nature', region: 'north', name: "Pai Canyon", lat: 19.3060, lng: 98.4526, price_thb: 0, desc: "Smalle zandsteenruggen met diepe afgronden, populair bij zonsondergang." },
    { rank: 39, type: 'sight', tag: 'culture', region: 'west', name: "Wat Tham Suea (Kanchanaburi)", lat: 13.9535, lng: 99.6053, price_thb: 0, desc: "Enorme gouden Boeddha op een heuvel met uitzicht over de rijstvelden." },
    { rank: 40, type: 'sight', tag: 'nature', region: 'west', name: "Sai Yok National Park", lat: 14.4397, lng: 98.8559, price_thb: 300, desc: "Watervallen die direct in de rivier de Kwai stromen en drijvende hotels." },
    { rank: 41, type: 'sight', tag: 'culture', region: 'bangkok', name: "Maeklong Railway Market", lat: 13.4075, lng: 99.9987, price_thb: 0, desc: "De unieke markt waar de trein dwars doorheen rijdt." },
    { rank: 42, type: 'sight', tag: 'culture', region: 'bangkok', name: "Bang Pa-In Palace", lat: 14.2323, lng: 100.5796, price_thb: 100, desc: "Zomerpaleis van de koningen met Thaise, Chinese en Europese architectuur." },
    { rank: 43, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chaloem Phra Kiat", lat: 18.7413, lng: 99.5436, price_thb: 200, desc: "Zwevende witte pagodes bovenop messcherpe kalksteenpieken." },
    { rank: 44, type: 'sight', tag: 'nature', region: 'south', name: "James Bond Island", lat: 8.2750, lng: 98.5000, price_thb: 300, desc: "De beroemde paddestoelvormige rots uit 'The Man with the Golden Gun'." },
    { rank: 45, type: 'sight', tag: 'nature', region: 'north', name: "Mae Hong Son Loop", lat: 19.3020, lng: 97.9654, price_thb: 0, desc: "Beroemde motorroute met 1864 bochten door de bergen." },
    { rank: 46, type: 'sight', tag: 'culture', region: 'bangkok', name: "Victory Monument", lat: 13.7649, lng: 100.5383, price_thb: 0, desc: "Militair monument en belangrijk knooppunt van lokaal leven." },
    { rank: 47, type: 'sight', tag: 'culture', region: 'south', name: "Big Buddha Phuket", lat: 7.8276, lng: 98.3126, price_thb: 0, desc: "Enorm wit marmeren beeld op een heuveltop met weids uitzicht." },
    { rank: 48, type: 'sight', tag: 'nature', region: 'east', name: "Nong Nooch Tropical Garden", lat: 12.7663, lng: 100.9335, price_thb: 500, desc: "Prachtig aangelegde botanische tuinen en cultuurshows in Pattaya." },
    { rank: 49, type: 'sight', tag: 'culture', region: 'west', name: "Mallika City", lat: 14.0436, lng: 99.2938, price_thb: 250, desc: "Levend museum dat het leven in 1905 nabootst (klederdracht verplicht)." },
    { rank: 50, type: 'sight', tag: 'culture', region: 'bangkok', name: "MOCA Bangkok", lat: 13.8523, lng: 100.5627, price_thb: 250, desc: "Museum met een indrukwekkende collectie moderne Thaise kunst." }
];