const sights_data = [
    { id: 101, rank: 1, type: 'sight', tag: 'culture', region: 'bangkok', name: "The Grand Palace", lat: 13.7500, lng: 100.4915, price: "€ 13,50", desc: "Het officiële verblijf van de koningen van Siam." },
    { id: 181, rank: 2, type: 'sight', tag: 'nature', region: 'south', name: "Phi Phi Islands (Maya Bay)", lat: 7.6775, lng: 98.7663, price: "€ 10,80", desc: "Wereldberoemde baai, nu ecologisch herstellende." },
    { id: 102, rank: 3, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Arun", lat: 13.7437, lng: 100.4888, price: "€ 5,40", desc: "Tempel van de Dageraad, iconisch om zijn centrale toren met porselein." },
    { id: 105, rank: 4, type: 'sight', tag: 'culture', region: 'bangkok', name: "Ayutthaya Historical Park", lat: 14.3532, lng: 100.5684, price: "€ 1,35", desc: "De oude hoofdstad, het hoogtepunt van de Siamese macht." },
    { id: 131, rank: 5, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Doi Suthep", lat: 18.8048, lng: 98.9216, price: "€ 0,80", desc: "Heilige tempel op een berg met uitzicht over Chiang Mai." },
    { id: 106, rank: 6, type: 'sight', tag: 'nature', region: 'south', name: "Khao Sok National Park", lat: 8.9135, lng: 98.5309, price: "€ 8,10", desc: "Oerwoud ouder dan de Amazone en drijvende huisjes." },
    { id: 109, rank: 7, type: 'sight', tag: 'nature', region: 'west', name: "Erawan National Park", lat: 14.3755, lng: 99.1440, price: "€ 8,10", desc: "Sprookjesachtige waterval met zeven niveaus." },
    { id: 132, rank: 8, type: 'sight', tag: 'culture', region: 'north', name: "Wat Rong Khun (Witte Tempel)", lat: 19.8243, lng: 99.7632, price: "€ 2,70", desc: "Een tempel als kunstwerk, symboliseert de overgang van de hel naar de hemel." },
    { id: 110, rank: 9, type: 'sight', tag: 'nature', region: 'south', name: "Railay Beach", lat: 8.0110, lng: 98.8373, price: "Gratis", desc: "Kalksteenkliffen en stranden, alleen per boot bereikbaar." },
    { id: 103, rank: 10, type: 'sight', tag: 'culture', region: 'bangkok', name: "Wat Pho", lat: 13.7465, lng: 100.4933, price: "€ 8,10", desc: "Huis van de liggende Boeddha en de eerste universiteit van Thailand." },
    { id: 153, rank: 11, type: 'sight', tag: 'nature', region: 'east', name: "Sam Pan Bok", lat: 15.8033, lng: 105.3855, price: "Gratis", desc: "De 'Grand Canyon' van Thailand in de Mekong-rivier." },
    { id: 113, rank: 12, type: 'sight', tag: 'culture', region: 'north', name: "Sukhothai Historical Park", lat: 17.0163, lng: 99.7036, price: "€ 2,70", desc: "De eerste hoofdstad van Siam, Unesco werelderfgoed." },
    { id: 183, rank: 13, type: 'sight', tag: 'nature', region: 'south', name: "Samet Nangshe Viewpoint", lat: 8.2406, lng: 98.4485, price: "€ 0,80", desc: "Het ultieme uitzicht over de baai van Phang Nga." },
    { id: 172, rank: 14, type: 'sight', tag: 'culture', region: 'west', name: "Bridge Over the River Kwai", lat: 14.0410, lng: 99.5042, price: "Gratis", desc: "Historische brug van de Dodenspoorlijn." },
    { id: 207, rank: 15, type: 'sight', tag: 'culture', region: 'east', name: "Sanctuary of Truth", lat: 12.9727, lng: 100.8891, price: "€ 13,50", desc: "Gigantisch houten monument aan zee, volledig handgesneden." },
    { id: 104, rank: 16, type: 'sight', tag: 'culture', region: 'bangkok', name: "Chatuchak Weekend Market", lat: 13.7998, lng: 100.5504, price: "Gratis", desc: "Grootste markt met 15.000 kraampjes." },
    { id: 185, rank: 17, type: 'sight', tag: 'nature', region: 'south', name: "Similan Islands", lat: 8.6536, lng: 97.6433, price: "€ 13,50", desc: "Wereldklasse duik- en snorkelplek (gesloten mei-okt)." },
    { id: 137, rank: 18, type: 'sight', tag: 'culture', region: 'north', name: "Wat Rong Suea Ten (Blauwe Tempel)", lat: 19.9233, lng: 99.8419, price: "Gratis", desc: "Opvallende blauwe tempel met een indrukwekkend interieur." },
    { id: 142, rank: 19, type: 'sight', tag: 'culture', region: 'east', name: "Phimai Historical Park", lat: 15.2203, lng: 102.4939, price: "€ 2,70", desc: "De grootste Khmer-tempel in Thailand." },
    { id: 187, rank: 20, type: 'sight', tag: 'nature', region: 'south', name: "Koh Lipe", lat: 6.4884, lng: 99.3039, price: "€ 5,40", desc: "De 'Malediven van Thailand' met turquoise water." },
    { id: 107, rank: 21, type: 'sight', tag: 'culture', region: 'bangkok', name: "Damnoen Saduak Market", lat: 13.5195, lng: 99.9577, price: "Gratis", desc: "De beroemdste drijvende markt van Thailand." },
    { id: 141, rank: 22, type: 'sight', tag: 'culture', region: 'east', name: "Phanom Rung Historical Park", lat: 14.5323, lng: 102.9426, price: "€ 2,70", desc: "Khmer-tempel op de rand van een uitgedoofde vulkaan." },
    { id: 119, rank: 23, type: 'sight', tag: 'culture', region: 'bangkok', name: "Asiatique The Riverfront", lat: 13.7045, lng: 100.5034, price: "Gratis", desc: "Shoppen en dineren aan de rivier in oude pakhuizen." },
    { id: 123, rank: 24, type: 'sight', tag: 'nature', region: 'north', name: "Elephant Nature Park", lat: 19.2155, lng: 98.8606, price: "€ 67,50", desc: "Pionier in ethische olifantenopvang." },
    { id: 139, rank: 25, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chaloem Phra Kiat", lat: 18.7413, lng: 99.5436, price: "€ 5,40", desc: "Zwevende pagodes op kalksteenpieken." },
    { id: 189, rank: 26, type: 'sight', tag: 'nature', region: 'south', name: "Ang Thong National Marine Park", lat: 9.6150, lng: 99.6766, price: "€ 8,10", desc: "Archipel van 42 eilanden, bekend van 'The Beach'." },
    { id: 125, rank: 27, type: 'sight', tag: 'culture', region: 'west', name: "Dragon Descendants Museum", lat: 14.4776, lng: 100.1106, price: "€ 13,00", desc: "Enorm drakenmuseum dat de Chinees-Thaise geschiedenis toont." },
    { id: 134, rank: 28, type: 'sight', tag: 'culture', region: 'north', name: "Wat Chedi Luang", lat: 18.7870, lng: 98.9866, price: "€ 1,10", desc: "De grote ruïne-stoepa in het oude centrum van Chiang Mai." },
    { id: 117, rank: 29, type: 'sight', tag: 'culture', region: 'bangkok', name: "Jim Thompson House", lat: 13.7495, lng: 100.5283, price: "€ 5,40", desc: "Traditioneel teakhouten huis van de zijdemythe." },
    { id: 188, rank: 30, type: 'sight', tag: 'nature', region: 'south', name: "Koh Tao", lat: 10.0956, lng: 99.8404, price: "Gratis", desc: "Het eiland om te leren duiken." },
    { id: 154, rank: 31, type: 'sight', tag: 'nature', region: 'east', name: "Red Lotus Lake", lat: 17.2210, lng: 103.0381, price: "€ 10,00", desc: "Meer vol roze waterlelies (seizoen: dec-feb)." },
    { id: 173, rank: 32, type: 'sight', tag: 'culture', region: 'west', name: "Hellfire Pass", lat: 14.3528, lng: 98.9536, price: "Gratis", desc: "Indrukwekkend herdenkingsmuseum en wandelroute." },
    { id: 194, rank: 33, type: 'sight', tag: 'nature', region: 'south', name: "Aiyerweng Skywalk", lat: 5.9757, lng: 101.1825, price: "€ 5,40", desc: "Glazen platform met uitzicht over de 'Zee van Mist' in Betong." },
    { id: 121, rank: 34, type: 'sight', tag: 'culture', region: 'bangkok', name: "Golden Mount (Wat Saket)", lat: 13.7538, lng: 100.5066, price: "€ 2,70", desc: "Tempel op een heuvel met uitzicht over oud Bangkok." },
    { id: 136, rank: 35, type: 'sight', tag: 'nature', region: 'north', name: "Pai Canyon", lat: 19.3060, lng: 98.4526, price: "Gratis", desc: "Smalle richels en zonsondergangen." },
    { id: 128, rank: 36, type: 'sight', tag: 'nature', region: 'east', name: "Koh Chang", lat: 12.0406, lng: 102.3023, price: "Gratis", desc: "Groot eiland met jungle en stranden." },
    { id: 135, rank: 37, type: 'sight', tag: 'culture', region: 'north', name: "Baan Dam (Black House)", lat: 19.9922, lng: 99.8605, price: "€ 2,15", desc: "Duister en artistiek museumcomplex." },
    { id: 122, rank: 38, type: 'sight', tag: 'culture', region: 'bangkok', name: "MahaNakhon SkyWalk", lat: 13.7224, lng: 100.5283, price: "€ 24,00", desc: "Glazen vloer op 314 meter hoogte." },
    { id: 155, rank: 39, type: 'sight', tag: 'culture', region: 'east', name: "Wat Phu Tok", lat: 18.1319, lng: 103.8827, price: "Gratis", desc: "Tempel met houten loopbruggen rondom een zandsteenrots." },
    { id: 124, rank: 40, type: 'sight', tag: 'culture', region: 'bangkok', name: "Lumpini Park", lat: 13.7314, lng: 100.5414, price: "Gratis", desc: "Het groene hart van de stad vol varanen." },
    { id: 158, rank: 41, type: 'sight', tag: 'nature', region: 'east', name: "Koh Kood", lat: 11.6667, lng: 102.5667, price: "Gratis", desc: "Rustig eiland met kristalhelder water." },
    { id: 148, rank: 42, type: 'sight', tag: 'culture', region: 'bangkok', name: "Talad Noi", lat: 13.7346, lng: 100.5133, price: "Gratis", desc: "Oudste wijk van Bangkok vol streetart." },
    { id: 156, rank: 43, type: 'sight', tag: 'culture', region: 'east', name: "Sala Keoku", lat: 17.8864, lng: 102.7786, price: "€ 1,10", desc: "Beeldentuin met bizarre, enorme cementen beelden." },
    { id: 137, rank: 44, type: 'sight', tag: 'nature', region: 'west', name: "Sai Yok National Park", lat: 14.4397, lng: 98.8559, price: "€ 8,10", desc: "Watervallen die direct in de rivier stromen." },
    { id: 115, rank: 45, type: 'sight', tag: 'culture', region: 'north', name: "Wat Phra That Doi Kong Mu", lat: 19.3003, lng: 97.9606, price: "Gratis", desc: "Tempel met Shan-invloeden en uitzicht over Mae Hong Son." },
    { id: 159, rank: 46, type: 'sight', tag: 'nature', region: 'east', name: "Koh Samet", lat: 12.5683, lng: 101.4526, price: "€ 5,40", desc: "Populair eiland voor een weekend weg vanuit Bangkok." },
    { id: 138, rank: 47, type: 'sight', tag: 'culture', region: 'bangkok', name: "Maeklong Railway Market", lat: 13.4075, lng: 99.9987, price: "Gratis", desc: "Markt op het trein spoor." },
    { id: 146, rank: 48, type: 'sight', tag: 'culture', region: 'north', name: "Su Tong Pae Bridge", lat: 19.3879, lng: 97.9542, price: "Gratis", desc: "Bamboe brug door de rijstvelden." },
    { id: 147, rank: 49, type: 'sight', tag: 'culture', region: 'east', name: "Prasat Muang Tam", lat: 14.4983, lng: 102.9819, price: "€ 2,70", desc: "Khmer tempel nabij Phanom Rung." },
    { id: 126, rank: 50, type: 'sight', tag: 'culture', region: 'bangkok', name: "Erawan Museum", lat: 13.6286, lng: 100.5890, price: "€ 10,80", desc: "Gigantische driehoofdige olifant." }
];
